### PR TITLE
Add valid-jsdoc rule

### PR DESCRIPTION
**Pull request by pvdlg**
Per sindresorhus/xo#282

### CODE REVIEW

**Comment by sindresorhus** [comment]
@simonepri Looks good?

**Comment by simonepri** [comment]
Hi @pvdlg Thanks!

## `prefer` option
I'm just not too much confident with my choose of values inside the `prefer` options of the `valid-jsdoc` rule.

Those are the annotations supported by the [Google Closure Compiler](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler):

<details><summary>Click to open</summary><p>

- `@abstract`
- `@const`
- `@constructor`
- `@define`
- `@deprecated`
- `@dict`
- `@enum`
- `@export`
- `@extends`
- `@externs`
- `@fileoverview`
- `@final`
- `@implements`
- `@implicitCast`
- `@inheritDoc`
- `@interface`
- `@record`
- `@lends`
- `@license`
- `@preserve`
- `@nocollapse`
- `@nosideeffects`
- `@modifies`
- `@override`
- `@package`
- `@param`
- `@polymer`
- `@polymerBehavior`
- `@private`
- `@protected`
- `@public`
- `@return`
- `@struct`
- `@suppress`
- `@template T`
- `@this`
- `@throws`
- `@type`
- `@typedef`
- `@unrestricted`
- `@noalias`
- `@nocompile

</p></details></br>

Those are the annotations described on [JSDoc3](http://usejsdoc.org/):

<details><summary>Click to expand</summary><p>

- `@abstract` (**synonyms**: `@virtual`)
- `@access`
- `@alias`
- `@async`
- `@augments` (**synonyms**: `@extends`)
- `@author`
- `@borrows`
- `@callback`
- `@class` (**synonyms**: `@constructor`)
- `@classdesc`
- `@constant` (**synonyms**: `@const`)
- `@constructs`
- `@copyright`
- `@default` (**synonyms**: `@defaultvalue`)
- `@deprecated`
- `@description` (**synonyms**: `@desc`)
- `@enum`
- `@event`
- `@example`
- `@exports`
- `@external` (**synonyms**: `@host`)
- `@file` (**synonyms**: `@fileoverview`, `@overview`)
- `@fires` (**synonyms**: `@emits`)
- `@function` (**synonyms**: `@func`, `@method`)
- `@generator`
- `@global`
- `@hideconstructor`
- `@ignore`
- `@implements`
- `@inheritdoc`
- `@inner`
- `@instance`
- `@interface`
- `@kind`
- `@lends`
- `@license`
- `@listens`
- `@member` (**synonyms**: `@var`)
- `@memberof`
- `@mixes`
- `@mixin`
- `@module`
- `@name`
- `@namespace`
- `@override`
- `@package`
- `@param` (**synonyms**: `@arg`, `@argument`)
- `@private`
- `@property` (**synonyms**: `@prop`)
- `@protected`
- `@public`
- `@readonly`
- `@requires`
- `@returns` (**synonyms**: `@return`)
- `@see`
- `@since`
- `@static`
- `@summary`
- `@this`
- `@throws` (**synonyms**: `@exception`)
- `@todo`
- `@tutorial`
- `@type`
- `@typedef`
- `@variation`
- `@version`
- `@yields` (**synonyms**: `@yield`)

</p></details></br>

These are the annotations supported by [JSDuck5](https://github.com/senchalabs/jsduck/wiki/New-in-jsduck-5):

<details><summary>Click to expand</summary><p>
- `@abstract`
- `@accessor`
- `@alias`
- `@alternateClassName`
- `@aside`
- `@author`
- `@cfg`
- `@chainable`
- `@class`
- `@constructor`
- `@deprecated`
- `@docauthor`
- `@enum`
- `@event`
- `@evented`
- `@experimental`
- `@extends`
- `@fires`
- `@ftype`
- `@hide`
- `@ignore`
- `@inheritable`
- `@inheritdoc`
- `@link`
- `@localdoc`
- `@markdown`
- `@member`
- `@method`
- `@mixins`
- `@new`
- `@override`
- `@param`
- `@preventable`
- `@private`
- `@property`
- `@protected`
- `@ptype`
- `@readonly`
- `@removed`
- `@requires`
- `@return`
- `@scss` mixin
- `@since`
- `@singleton`
- `@static`
- `@template`
- `@throws`
- `@type`
- `@uses`
- `@var`
- `@xtype`

</p></details></br>

I've done some research and I've re-elaborated it, let's discuss.
```
"prefer": {
  "arg": "param",             // param is supported by all, arg by JSDoc only
  "argument": "param",        // param is supported by all, argument by JSDoc only
  "augments": "extends",      // extends is supported by all, arguments by JSDoc only
  "constant": "const",        // const is supported by JSDoc and Closure Compile, constant by JSDoc only
  "defaultvalue": "default",  // Both are supported only by JSDoc, let's use the one that JSDoc suggests
  "desc": "description",      // Both are supported only by JSDoc, let's use the one that JSDoc suggests
  "exception": "throws",      // throws is supperted by all, exception by JSDoc only
  "emits": "fires",           // fires is supported by JSDoc and JSDuck, emits only by JSDoc
  "func": "method",           // method is supported by JSDoc and JSDuck, func only by JSDoc
  "function": "method",       // method is supported by JSDoc and JSDuck, function only by JSDoc
  "prop": "property",         // property is supported by JSDoc and JSDuck
  "return": "returns",        // Force pluralization for cosistency (fires, extends, throws, etc)
  "virtual": "abstract",      // abstract is supported by all, virtual by JSDoc only
  "yeld": "yelds"             // Force pluralization for cosistency (fires, extends, throws, etc)
},
```

## `preferType` option
I believe it's more readable if we rewrite it in lexicographical order.
Also `function`, `null` and `undefined` are missing.
```
"preferType": {
  "Boolean": "boolean",
  "Null": "null",
  "Number": "number",
  "String": "string",
  "Undefined": "undefined",
  "array": "Array",
  "function": "Function",
  "date": "Date",
  "object": "Object",
  "regex": "RegExp"
}
```

**Comment by pvdlg** [comment]
Considering the discrepancies between the different JSDoc implementation and the the lack of standard, it might be better to not set `prefer` and `preferType`. 

Also using `Boolean` vs `boolean` and similar is quite opinionated. So I'm really not sure those 2 params are a good idea...

**Comment by sindresorhus** [comment]
What do we want to do about this?

**Comment by simonepri** [comment]
As @pvdlg pointed out maybe is better to not provide defaults for `prefer` and `preferType` options at all.

**Comment by pvdlg** [comment]
Can you update the PR with this change?

**Comment by pvdlg** [comment]
The PR is actually mine. I updated it to use default values for `preferType` and `prefer` :)

**Pull request merged**
